### ISSUE TITLE
bopp.tk can't be reached

### ISSUE THREAD

**Issue by robtech21** [nobody5050/bopp#3]
When I try to go to [bopp.tk](https://bopp.tk) it said it couldn't be reached and gave the error message `DNS_PROBE_FINISHED_NXDOMAIN`. Is the domain not registered?

Update: I pinged the domain and it returned `name or service not known` so it's not registered or online.

**Comment by nobody5050** [comment]
Was a CNAME issue. pinging www.bopp.tk should work no matter what. Regular domain should be fixed in commit 4bf0d99

**Comment by nobody5050** [comment]
Issue has reappeared, currently investigating

**Comment by nobody5050** [comment]
The issue has been resolved
